from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import os



def generate_pdf_report(profile, recommendations):

    report_folder = "reports/generated"

    os.makedirs(
        report_folder,
        exist_ok=True
    )


    filename = (
        "AI_Resume_Analysis_Report_"
        + datetime.now().strftime("%Y%m%d_%H%M%S")
        + ".pdf"
    )


    file_path = os.path.join(
        report_folder,
        filename
    )


    document = SimpleDocTemplate(
        file_path,
        pagesize=letter
    )


    styles = getSampleStyleSheet()


    content = []


    # Title

    content.append(
        Paragraph(
            "AI Resume Screening Report",
            styles["Title"]
        )
    )

    content.append(
        Spacer(1, 20)
    )


    content.append(
        Paragraph(
            "Generated by AI Resume Screening System",
            styles["Normal"]
        )
    )


    content.append(
        Spacer(1, 20)
    )



    # Candidate Information

    content.append(
        Paragraph(
            "Candidate Information",
            styles["Heading2"]
        )
    )


    candidate_data = [

        ["Name", profile.get("name")],

        ["Email", profile.get("email")],

        ["Phone", profile.get("phone")]

    ]


    table = Table(candidate_data)


    table.setStyle(
        TableStyle(
            [
                ("GRID",(0,0),(-1,-1),0.5,None)
            ]
        )
    )


    content.append(table)

    content.append(
        Spacer(1,20)
    )



    # Skills

    content.append(
        Paragraph(
            "Skills",
            styles["Heading2"]
        )
    )


    skills = ", ".join(
        profile.get("skills", [])
    )


    content.append(
        Paragraph(
            skills,
            styles["Normal"]
        )
    )


    content.append(
        Spacer(1,20)
    )



    # Education

    content.append(
        Paragraph(
            "Education",
            styles["Heading2"]
        )
    )


    for edu in profile.get("education", []):

        content.append(
            Paragraph(
                "• " + edu,
                styles["Normal"]
            )
        )



    content.append(
        Spacer(1,20)
    )



    # Projects

    content.append(
        Paragraph(
            "Projects",
            styles["Heading2"]
        )
    )


    for project in profile.get("projects", []):

        content.append(
            Paragraph(
                "• " + project,
                styles["Normal"]
            )
        )



    content.append(
        Spacer(1,20)
    )



    # Job Recommendations

    content.append(
        Paragraph(
            "Recommended Jobs",
            styles["Heading2"]
        )
    )


    job_data = [

        [
            "Job Role",
            "Company",
            "Score"
        ]

    ]


    for job in recommendations[:5]:

        job_data.append(
            [
                job["job_title"],
                job["company"],
                str(job["score"]) + "%"
            ]
        )


    job_table = Table(job_data)


    job_table.setStyle(
        TableStyle(
            [
                ("GRID",(0,0),(-1,-1),0.5,None)
            ]
        )
    )


    content.append(
        job_table
    )



    document.build(content)


    return file_path